# -*- coding: utf-8 -*-

NO_VIDEO = None

GROUPS = [
    {
        "id": "last-word",
        "title": "The Last Word & Its Equal-Parts Descendants",
        "intro": "A family built on the Last Word's equal-parts template: spirit, herbal liqueur, bittersweet element, citrus. Two of these need Chartreuse, which is the one genuinely hard bottle on the list — substitutions are noted in each build. The other two need none at all.",
        "cocktails": [
            {
                "n": 1, "name": "Last Word", "family": "Last Word family", "spirit": "Gin",
                "ing": ["¾ oz gin", "¾ oz green Chartreuse", "¾ oz maraschino liqueur (Luxardo)", "¾ oz fresh lime juice"],
                "method": "Shake with ice; strain up into a chilled coupe; no garnish (optional cherry). If you cannot find green Chartreuse, Faccia Brutto Centerbe or Dolin Génépy le Chamois both work; the drink gets softer and less peppery but stays recognisable.",
                "video": "https://www.youtube.com/watch?v=HsHQ2NFXMfE", "channel": "The Educated Barfly",
                "note": "Prohibition-era Detroit Athletic Club drink revived by Murray Stenson at Seattle's Zig Zag Café in the 2000s. The blueprint for everything else in this group.",
            },
            {
                "n": 2, "name": "Naked & Famous", "family": "Last Word family", "spirit": "Mezcal",
                "ing": ["¾ oz mezcal", "¾ oz yellow Chartreuse", "¾ oz Aperol", "¾ oz fresh lime juice"],
                "method": "Shake; double-strain up into a coupe; no garnish. Strega substitutes for yellow Chartreuse — sweeter and more saffron-forward, so pull it back to ⅔ oz and add a touch more lime.",
                "video": "https://www.youtube.com/watch?v=cAZyQ9GA6Gk", "channel": "The Educated Barfly",
                "note": "Joaquín Simó, Death &amp; Co, 2011. He described it as the bastard love child of a Last Word and a Paper Plane, conceived in the mountains of Oaxaca.",
            },
            {
                "n": 3, "name": "Paper Plane", "family": "Last Word family", "spirit": "Bourbon",
                "ing": ["¾ oz bourbon", "¾ oz Aperol", "¾ oz Amaro Nonino Quintessentia", "¾ oz fresh lemon juice"],
                "method": "Shake; strain up into a coupe.",
                "video": "https://www.youtube.com/watch?v=FveQ2xPFlnk", "channel": "How to Drink",
                "note": "Sam Ross with Sasha Petraske, 2008, for The Violet Hour in Chicago. The original ran Campari before Aperol was substituted.",
            },
            {
                "n": 5, "name": "Division Bell", "family": "Last Word family", "spirit": "Mezcal",
                "ing": ["1 oz mezcal", "¾ oz Aperol", "½ oz maraschino liqueur", "¾ oz fresh lime juice"],
                "method": "Shake; strain up; grapefruit twist.",
                "video": NO_VIDEO, "channel": None,
                "note": "Another Phil Ward riff, from Mayahuel. Smokier and drier than the Naked &amp; Famous; specs vary between equal parts and this weighted build.",
            },
        ],
    },
    {
        "id": "negroni",
        "title": "Negroni & Boulevardier Riffs",
        "intro": "Spirit, bitter liqueur, fortified wine. Run the same structure through whiskey, gin, rum and tequila and you get four genuinely different drinks — the clearest demonstration on this list of how much the base carries.",
        "cocktails": [
            {
                "n": 6, "name": "Boulevardier", "family": "Negroni riff", "spirit": "Bourbon / Rye",
                "ing": ["1½ oz bourbon or rye", "¾ oz sweet vermouth", "¾ oz Campari"],
                "method": "Stir; strain over a large cube in a rocks glass; orange twist. The 1927 original is equal parts; Difford's favours 3:2:2.",
                "video": "https://www.youtube.com/watch?v=9Pey-ulGNRY", "channel": "The Educated Barfly",
                "note": "The whiskey Negroni, from Harry McElhone's Barflies and Cocktails (1927) and credited to Erskine Gwynne.",
            },
            {
                "n": 7, "name": "White Negroni", "family": "Negroni riff", "spirit": "Gin",
                "ing": ["1½ oz gin", "¾–1 oz Suze (gentian liqueur)", "¾–1 oz Lillet Blanc"],
                "method": "Stir; rocks or up; grapefruit or lemon twist. A lighter 1.5 : 0.75 : 0.75 keeps Suze in check.",
                "video": "https://www.youtube.com/watch?v=pDDZO5WFOF0", "channel": "The Educated Barfly",
                "note": "Wayne Collins, c. 2001. Gentian and Lillet in place of Campari and sweet vermouth — pale, dry, and bitter in an entirely different register.",
            },
            {
                "n": 8, "name": "Kingston Negroni", "family": "Negroni riff", "spirit": "Rum",
                "ing": ["1 oz Smith &amp; Cross overproof Jamaican rum", "1 oz Campari", "1 oz sweet vermouth"],
                "method": "Stir; rocks over a large cube; orange twist.",
                "video": NO_VIDEO, "channel": None,
                "note": "Joaquín Simó's rum Negroni. Funky pot-still hogo turns the template tropical and very intense.",
            },
            {
                "n": 9, "name": "Rosita", "family": "Negroni riff", "spirit": "Tequila",
                "ing": ["1½ oz reposado tequila", "½ oz Campari", "½ oz sweet vermouth", "½ oz dry vermouth", "dash Angostura"],
                "method": "Stir; rocks; lemon twist.",
                "video": NO_VIDEO, "channel": None,
                "note": "A tequila Negroni popularised by Gary Regan. The split vermouths keep it dry where a straight swap would go syrupy.",
            },
            {
                "n": 10, "name": "Old Pal", "family": "Negroni riff", "spirit": "Rye",
                "ing": ["1 oz rye whiskey", "1 oz dry vermouth", "1 oz Campari"],
                "method": "Stir; strain up into a coupe; lemon twist.",
                "video": "https://www.youtube.com/watch?v=BkUUHnEc5_c", "channel": "The Educated Barfly",
                "note": "The Boulevardier's austere cousin — dry vermouth instead of sweet. Another McElhone recipe.",
            },
        ],
    },
    {
        "id": "amaro",
        "title": "Amaro-Driven & Bitter-Forward",
        "intro": "Drinks where the bitter is the subject rather than the seasoning. This group trains the palate on Italian amari, Fernet, Cynar, and — in one famous case — Angostura used as a base spirit.",
        "cocktails": [
            {
                "n": 11, "name": "Americano", "family": "Aperitivo", "spirit": "Amaro",
                "ing": ["1½ oz Campari", "1½ oz sweet vermouth", "soda water to top"],
                "method": "Build over ice in a highball; orange half-wheel.",
                "video": "https://www.youtube.com/watch?v=TmeUJ2g3ogM", "channel": "The Educated Barfly",
                "note": "The low-ABV ancestor of the Negroni and the gentlest possible entry into bitter drinking.",
            },
            {
                "n": 12, "name": "Black Manhattan", "family": "Amaro-forward", "spirit": "Rye",
                "ing": ["2 oz rye whiskey (100 proof)", "1 oz Amaro Averna", "1 dash Angostura", "1 dash orange bitters"],
                "method": "Stir; fine-strain up into a coupe; cherry.",
                "video": "https://www.youtube.com/watch?v=kx7KaY8fPsw", "channel": "Steve the Bartender",
                "note": "Todd Smith at Bourbon &amp; Branch, San Francisco, c. 2005. Averna replaces the vermouth entirely — bitter chocolate, cola, and spice.",
            },
            {
                "n": 13, "name": "Toronto", "family": "Amaro-forward", "spirit": "Rye",
                "ing": ["2 oz rye whiskey", "¼ oz Fernet-Branca", "¼ oz demerara or simple syrup", "2 dashes Angostura"],
                "method": "Stir; strain up; orange twist.",
                "video": "https://www.youtube.com/watch?v=IzA0Rc89Qa8", "channel": "The Educated Barfly",
                "note": "A menthol-bitter Old Fashioned variation and the best possible introduction to Fernet in small doses.",
            },
            {
                "n": 14, "name": "Trinidad Sour", "family": "Bitter-forward", "spirit": "Amaro / Bitters",
                "ing": ["1½ oz Angostura bitters", "1 oz orgeat", "¾ oz fresh lemon juice", "½ oz rye whiskey"],
                "method": "Shake; strain up into a coupe. Homemade orgeat pays off here more than anywhere.",
                "video": NO_VIDEO, "channel": None,
                "note": "Giuseppe González, Clover Club, 2009. It flopped at the competition it was made for, failing to place in the top ten, then became a modern classic built on an entire bottle of Angostura.",
            },
            {
                "n": 15, "name": "Hanky Panky", "family": "Amaro-accented", "spirit": "Gin",
                "ing": ["1½ oz gin", "1½ oz sweet vermouth", "2 dashes Fernet-Branca"],
                "method": "Stir; strain up; orange twist.",
                "video": "https://www.youtube.com/watch?v=pdAo67PVz0Y", "channel": "The Educated Barfly",
                "note": "Ada Coleman at the Savoy, c. 1903 — one of the first canonical cocktails created by a celebrated woman behind a bar.",
            },
            {
                "n": 16, "name": "Bitter Giuseppe", "family": "Amaro-forward", "spirit": "Amaro",
                "ing": ["2 oz Cynar", "1 oz sweet vermouth", "¼ oz fresh lemon juice", "6 dashes orange bitters"],
                "method": "Stir; rocks; lemon twist.",
                "video": NO_VIDEO, "channel": None,
                "note": "Stephen Cole, The Violet Hour. Proof that artichoke amaro can anchor a whole drink rather than hide inside one.",
            },
        ],
    },
    {
        "id": "nola",
        "title": "New Orleans & Spirit-Forward Whiskey",
        "intro": "Deep, stirred, aromatic whiskey drinks heavy on Bénédictine and Peychaud's, plus two modern sours that have already earned classic status and one Brooklyn-era stirred drink that spawned a family of its own.",
        "cocktails": [
            {
                "n": 17, "name": "À La Louisiane", "family": "New Orleans whiskey", "spirit": "Rye",
                "ing": ["¾ oz rye", "¾ oz sweet vermouth", "¾ oz Bénédictine", "3 dashes absinthe", "3 dashes Peychaud's bitters"],
                "method": "Stir; strain up; cherry.",
                "video": "https://www.youtube.com/watch?v=A6EKg9BSAIs", "channel": "The Educated Barfly",
                "note": "House cocktail of Restaurant de la Louisiane. A richer, absinthe-laced sibling to the Vieux Carré.",
            },
            {
                "n": 18, "name": "Benton's Old Fashioned", "family": "Modern technique", "spirit": "Bourbon",
                "ing": ["2 oz bacon-fat-washed bourbon", "¼ oz Grade B maple syrup", "2 dashes Angostura"],
                "method": "Stir; rocks over a large cube; orange twist. To fat-wash: infuse bourbon with warm rendered bacon fat, freeze solid, strain off the fat.",
                "video": "https://www.youtube.com/watch?v=TQVUcdXCw6I", "channel": "The Educated Barfly",
                "note": "Don Lee at PDT, 2007 — the drink that put fat-washing on every serious bar menu.",
            },
            {
                "n": 19, "name": "Gold Rush", "family": "Modern whiskey sour", "spirit": "Bourbon",
                "ing": ["2 oz bourbon", "¾ oz honey syrup (3:1 honey to water)", "¾ oz fresh lemon juice"],
                "method": "Shake; strain over a large cube; lemon twist.",
                "video": "https://www.youtube.com/watch?v=cw1auKW__v4", "channel": "The Educated Barfly",
                "note": "T.J. Siegal at Milk &amp; Honey. Three ingredients, no room to hide — the honey syrup ratio is the whole drink.",
            },
            {
                "n": 20, "name": "Penicillin", "family": "Modern Scotch sour", "spirit": "Scotch",
                "ing": ["2 oz blended Scotch", "¾ oz fresh lemon juice", "¾ oz honey-ginger syrup", "¼ oz Islay single malt, floated"],
                "method": "Shake the first three; strain over ice; float the Islay; candied ginger.",
                "video": "https://www.youtube.com/watch?v=u02e6z_qE1I", "channel": "Truffle on the Rocks",
                "note": "Sam Ross, Milk &amp; Honey, 2005. Robert Simonson has called it one of the most travelled new cocktails of the century.",
            },
            {
                "n": 0, "name": "Red Hook", "family": "Brooklyn variation", "spirit": "Rye",
                "ing": ["2 oz rye whiskey", "½ oz Punt e Mes", "½ oz maraschino liqueur"],
                "method": "Stir; strain up into a Nick &amp; Nora; cherry. Some sources call for ¼ oz maraschino — start there if you prefer it drier.",
                "video": NO_VIDEO, "channel": None,
                "note": "Vincenzo Errico at Milk &amp; Honey, 2003–04, built on the Brooklyn rather than the Manhattan by swapping Amer Picon for Punt e Mes. It set off a whole run of rye drinks named for Brooklyn neighbourhoods — Greenpoint, Bensonhurst, Cobble Hill, Carroll Gardens.",
            },
        ],
    },
    {
        "id": "gin",
        "title": "Gin: Golden Age & Modern",
        "intro": "Pre-Prohibition elegance plus two moderns, covering gin's full range from floral to herbaceous to the most demanding shake in the book.",
        "cocktails": [
            {
                "n": 21, "name": "Corpse Reviver No. 2", "family": "Golden Age gin", "spirit": "Gin",
                "ing": ["¾ oz London dry gin", "¾ oz Cointreau", "¾ oz Cocchi Americano (or Lillet Blanc)", "¾ oz fresh lemon juice", "absinthe rinse"],
                "method": "Shake; fine-strain up; lemon or orange twist.",
                "video": NO_VIDEO, "channel": None,
                "note": "From the Savoy Cocktail Book, 1930, with Craddock's warning that four in swift succession will unrevive the corpse again.",
            },
            {
                "n": 22, "name": "Bee's Knees", "family": "Golden Age gin", "spirit": "Gin",
                "ing": ["2 oz gin", "¾ oz fresh lemon juice", "¾ oz honey syrup"],
                "method": "Shake; strain up; lemon twist.",
                "video": "https://www.youtube.com/watch?v=hveWIAcYVkE", "channel": "The Educated Barfly",
                "note": "Prohibition-era, where the honey was there to cover bathtub gin. With good gin it becomes one of the great three-ingredient sours.",
            },
            {
                "n": 23, "name": "Clover Club", "family": "Golden Age gin", "spirit": "Gin",
                "ing": ["1½ oz gin", "½ oz fresh lemon juice", "½ oz raspberry syrup", "½ oz egg white"],
                "method": "Dry-shake, then shake with ice; strain up; raspberries.",
                "video": "https://www.youtube.com/watch?v=Ui7dOJkmpl4", "channel": "The Educated Barfly",
                "note": "A pre-Prohibition Philadelphia men's-club drink that is far more serious than its colour suggests.",
            },
            {
                "n": 24, "name": "Ramos Gin Fizz", "family": "Golden Age gin", "spirit": "Gin",
                "ing": ["2 oz gin", "½ oz lemon juice", "½ oz lime juice", "¾ oz simple syrup", "1 egg white", "1 oz heavy cream", "2–3 dashes orange flower water", "soda to top"],
                "method": "Dry-shake hard, shake with ice, strain into a chilled fizz glass, then top with soda to lift the head.",
                "video": "https://www.youtube.com/watch?v=rMRf3858Yrg", "channel": "The Educated Barfly",
                "note": "Henry Ramos, New Orleans, 1888. The endurance event of home bartending — split the shaking between the two of you.",
            },
            {
                "n": 25, "name": "Gin Basil Smash", "family": "Modern gin", "spirit": "Gin",
                "ing": ["2 oz gin", "¾ oz fresh lemon juice", "¾ oz simple syrup", "large handful fresh basil"],
                "method": "Muddle basil, shake hard, double-strain over ice; basil sprig.",
                "video": "https://www.youtube.com/watch?v=pLKuQvCiHUI", "channel": "The Educated Barfly",
                "note": "Jörg Meyer, Hamburg, 2008. Vividly green and one of the few modern classics to come out of Germany.",
            },
            {
                "n": 26, "name": "Aviation", "family": "Golden Age gin", "spirit": "Gin",
                "ing": ["2 oz gin", "½ oz maraschino liqueur", "¼ oz crème de violette", "¾ oz fresh lemon juice"],
                "method": "Shake; strain up; cherry. Keep the violette at ¼ oz — more and it turns soapy.",
                "video": NO_VIDEO, "channel": None,
                "note": "Hugo Ensslin, 1916. The reason crème de violette exists on modern back bars at all.",
            },
        ],
    },
    {
        "id": "tiki",
        "title": "Tiki & Rum-Forward",
        "intro": "The most ingredient-hungry group on the list: orgeat, falernum, allspice dram, demerara syrup and a lot of crushed ice. It is also a tour of rum from Jamaica to Barbados to Martinique, ending with a drink that hands the base over to Campari.",
        "cocktails": [
            {
                "n": 27, "name": "Jungle Bird", "family": "Tiki", "spirit": "Rum",
                "ing": ["1½ oz blackstrap or dark rum", "¾ oz Campari", "1½ oz pineapple juice", "½ oz fresh lime juice", "½ oz demerara syrup (2:1)"],
                "method": "Shake; strain over crushed ice; pineapple wedge and cherry.",
                "video": NO_VIDEO, "channel": None,
                "note": "Created 6 July 1973 at the Aviary Bar of the Kuala Lumpur Hilton by Jeffrey Ong Swee Teik. The drink that proved Campari belongs in the tropics.",
            },
            {
                "n": 28, "name": "Mai Tai", "family": "Tiki", "spirit": "Rum",
                "ing": ["2 oz aged Jamaican rum (or split with rhum agricole)", "½ oz dry orange curaçao", "¾ oz fresh lime juice", "¼ oz orgeat", "¼ oz demerara syrup"],
                "method": "Shake with crushed ice; rocks; mint and the spent lime shell.",
                "video": "https://www.youtube.com/watch?v=w1GFO5jtovY", "channel": "The Educated Barfly",
                "note": "Trader Vic, 1944. Martin Cate's Smuggler's Cove build is the modern benchmark and worth following exactly.",
            },
            {
                "n": 29, "name": "Three Dots and a Dash", "family": "Tiki", "spirit": "Rum",
                "ing": ["1½ oz rhum agricole vieux", "½ oz aged blended rum", "½ oz fresh lime juice", "½ oz fresh orange juice", "½ oz honey syrup", "¼ oz falernum", "¼ oz allspice dram", "1 dash Angostura"],
                "method": "Flash-blend with crushed ice; footed pilsner; three cherries and a pineapple frond.",
                "video": "https://www.youtube.com/watch?v=usz9Feoj5ag", "channel": "The Educated Barfly",
                "note": "Donn Beach, wartime. The garnish spells V for victory in Morse code — three dots and a dash.",
            },
            {
                "n": 31, "name": "Painkiller", "family": "Tiki", "spirit": "Rum",
                "ing": ["2 oz Pusser's navy rum", "4 oz pineapple juice", "1 oz orange juice", "1 oz cream of coconut"],
                "method": "Shake or swizzle; crushed ice; heavy grating of fresh nutmeg.",
                "video": "https://www.youtube.com/watch?v=3pHPDjeJviY", "channel": "Steve the Bartender",
                "note": "The trademarked house drink of the British Virgin Islands. Richer and far simpler than a Piña Colada.",
            },
            {
                "n": 32, "name": "Hemingway Daiquiri", "family": "Rum sour", "spirit": "Rum",
                "ing": ["2 oz white rum", "¾ oz fresh lime juice", "½ oz fresh grapefruit juice", "½ oz maraschino liqueur"],
                "method": "Shake; strain up; lime wheel.",
                "video": "https://www.youtube.com/watch?v=pKbISuGkKBI", "channel": "The Educated Barfly",
                "note": "La Floridita, Havana. Bone dry with no added sugar in the classic build — the maraschino is doing all of it.",
            },
            {
                "n": 33, "name": "Corn 'n' Oil", "family": "Rum-forward", "spirit": "Rum",
                "ing": ["2 oz blackstrap rum", "½ oz velvet falernum", "¼ oz fresh lime juice", "dash Angostura"],
                "method": "Build over crushed ice; lime.",
                "video": "https://www.youtube.com/watch?v=LWga1n7uVEc", "channel": "The Educated Barfly",
                "note": "Barbadian, molasses-dark, and built entirely around falernum. Four ingredients and completely unlike anything else here.",
            },
            {
                "n": 0, "name": "Bitter Mai Tai", "family": "Tiki / bitter-forward", "spirit": "Amaro",
                "ing": ["1½ oz Campari", "¾ oz aged Jamaican rum", "¾ oz fresh lime juice", "½ oz orgeat", "½ oz dry orange curaçao"],
                "method": "Shake; pour over crushed ice in a rocks glass; mint and the spent lime shell.",
                "video": NO_VIDEO, "channel": None,
                "note": "Shingo Gokan, Angel's Share, New York, 2011. Campari takes over as the base and the orgeat keeps it from going austere — the group's clearest bridge between tiki and aperitivo.",
            },
        ],
    },
    {
        "id": "agave",
        "title": "Agave: Tequila & Mezcal",
        "intro": "Everything past the Margarita — an Old Fashioned riff, a Campari sour, and two grapefruit-driven refreshers that belong in high summer.",
        "cocktails": [
            {
                "n": 34, "name": "Oaxaca Old Fashioned", "family": "Agave spirit-forward", "spirit": "Tequila / Mezcal",
                "ing": ["1½ oz reposado tequila", "½ oz mezcal", "1 tsp agave nectar", "2 dashes Angostura or mole bitters"],
                "method": "Stir; rocks over a large cube; flamed orange twist.",
                "video": "https://www.youtube.com/watch?v=nk7Nld2gRR8", "channel": "The Educated Barfly",
                "note": "Phil Ward, Death &amp; Co, 2007. The drink that moved mezcal from curiosity to staple.",
            },
            {
                "n": 35, "name": "Siesta", "family": "Agave sour", "spirit": "Tequila",
                "ing": ["2 oz blanco tequila", "½ oz Campari", "½ oz fresh lime juice", "½ oz fresh grapefruit juice", "½ oz simple syrup"],
                "method": "Shake; strain up; grapefruit twist.",
                "video": NO_VIDEO, "channel": None,
                "note": "Katie Stipe, 2006 — a Hemingway Daiquiri rebuilt on tequila with Campari doing the bittering.",
            },
            {
                "n": 36, "name": "Paloma", "family": "Agave refresher", "spirit": "Tequila",
                "ing": ["2 oz blanco tequila", "½ oz fresh lime juice", "pinch of salt", "grapefruit soda to top"],
                "method": "Build in a salt-rimmed highball over ice; grapefruit and lime.",
                "video": "https://www.youtube.com/watch?v=9_3h0OWYUtA", "channel": "The Educated Barfly",
                "note": "Mexico's actual favourite tequila drink, and a better hot-afternoon proposition than the Margarita.",
            },
            {
                "n": 37, "name": "Tommy's Margarita", "family": "Agave sour", "spirit": "Tequila",
                "ing": ["2 oz blanco tequila", "1 oz fresh lime juice", "½ oz agave nectar"],
                "method": "Shake; rocks, salt optional; lime.",
                "video": "https://www.youtube.com/watch?v=vuX41f3-5Eg", "channel": "The Educated Barfly",
                "note": "Julio Bermejo, San Francisco. Dropping the orange liqueur for agave leaves nothing between you and the tequila.",
            },
        ],
    },
    {
        "id": "brandy",
        "title": "Brandy & Cognac: Historical Elegance",
        "intro": "The oldest DNA in the book — the drinks American bartending was built on before whiskey took over — plus one South American classic.",
        "cocktails": [
            {
                "n": 38, "name": "Vieux Carré", "family": "Cognac / rye", "spirit": "Cognac",
                "ing": ["¾ oz rye", "¾ oz cognac", "¾ oz sweet vermouth", "½ oz Bénédictine", "2 dashes Peychaud's", "1 dash Angostura"],
                "method": "Stir; rocks; lemon twist and cherry. Specs vary — some use 1 oz each with only a barspoon of Bénédictine.",
                "video": "https://www.youtube.com/watch?v=_56K4-vdrik", "channel": "The Educated Barfly",
                "note": "Walter Bergeron, Hotel Monteleone, 1930s. The definitive New Orleans stirred drink.",
            },
            {
                "n": 39, "name": "Brandy Crusta", "family": "Historical brandy", "spirit": "Cognac",
                "ing": ["2 oz cognac", "½ oz dry curaçao", "¼ oz maraschino liqueur", "¾ oz fresh lemon juice", "¼ oz simple syrup", "2 dashes Angostura"],
                "method": "Shake; strain into a sugar-rimmed glass lined with a whole lemon-peel spiral.",
                "video": "https://www.youtube.com/watch?v=N0aPVPdLyQc", "channel": "Anders Erickson",
                "note": "Joseph Santini, New Orleans, 1850s. Ancestor of the Sidecar and the origin of the sugared crusta rim.",
            },
            {
                "n": 40, "name": "Japanese Cocktail", "family": "Historical brandy", "spirit": "Cognac",
                "ing": ["2 oz cognac", "½ oz orgeat", "2 dashes Angostura or Boker's bitters"],
                "method": "Stir; strain up; lemon twist.",
                "video": "https://www.youtube.com/watch?v=Ile399qAa1w", "channel": "The Educated Barfly",
                "note": "One of the few drinks Jerry Thomas actually invented, published 1862. Three ingredients, stirred, and unexpectedly modern.",
            },
            {
                "n": 0, "name": "Saratoga", "family": "Historical brandy", "spirit": "Cognac",
                "ing": ["1 oz cognac", "1 oz rye whiskey", "1 oz sweet vermouth", "2 dashes Angostura"],
                "method": "Stir; strain up; lemon twist or cherry.",
                "video": NO_VIDEO, "channel": None,
                "note": "Published by Jerry Thomas in 1887 and still barely known. Splitting the base between cognac and rye gives it a depth a straight Manhattan cannot reach.",
            },
            {
                "n": 42, "name": "Pisco Sour", "family": "Grape brandy sour", "spirit": "Pisco",
                "ing": ["2 oz pisco", "¾ oz fresh lime or lemon juice", "¾ oz simple syrup", "1 egg white", "3 drops Angostura on the foam"],
                "method": "Dry-shake, then shake with ice; strain up.",
                "video": NO_VIDEO, "channel": None,
                "note": "The national cocktail of both Peru and Chile, which is its own long argument. Pisco is a grape brandy, so it belongs in this family.",
            },
        ],
    },
    {
        "id": "apple",
        "title": "Apple Brandy, Revivers & Punch",
        "intro": "Autumnal and communal. An apple-brandy sour, a spirit-forward reviver, and one large-format punch for when the two of you have company.",
        "cocktails": [
            {
                "n": 0, "name": "Jack Rose", "family": "Apple brandy sour", "spirit": "Apple brandy",
                "ing": ["2 oz bonded apple brandy or applejack", "¾ oz fresh lemon or lime juice", "½ oz grenadine (homemade pomegranate)"],
                "method": "Shake; strain up; lemon twist or apple slice. Lemon reads sweeter, lime sharper — worth making both.",
                "video": NO_VIDEO, "channel": None,
                "note": "An early-1900s American classic that turns up repeatedly in Hemingway's The Sun Also Rises. It lives or dies on real pomegranate grenadine rather than the corn-syrup kind.",
            },
            {
                "n": 44, "name": "Corpse Reviver No. 1", "family": "Apple brandy / cognac", "spirit": "Cognac",
                "ing": ["1½ oz cognac", "¾ oz apple brandy or Calvados", "¾ oz sweet vermouth"],
                "method": "Stir; strain up; optional lemon twist.",
                "video": "https://www.youtube.com/watch?v=YblPFVgPEKE", "channel": "The Educated Barfly",
                "note": "The forgotten, spirit-forward sibling of the No. 2 — to be taken before eleven in the morning, when steam and energy are needed.",
            },
            {
                "n": 45, "name": "Fish House Punch", "family": "Batched punch", "spirit": "Cognac / Rum",
                "ing": ["Batch, serves 12–15: 750 ml cognac", "750 ml Jamaican dark rum", "4 oz peach brandy", "12 oz fresh lemon juice", "1 cup rich demerara syrup", "~1 L water or soda"],
                "method": "Combine over a large ice block; serve in punch cups. Single serve: 1 oz cognac, 1 oz dark rum, ½ oz peach brandy, ¾ oz lemon, ½ oz rich syrup, splash of water.",
                "video": "https://www.youtube.com/shorts/oeWx50szteM", "channel": "The Educated Barfly (Short)",
                "note": "Philadelphia, 1732 — colonial-era and genuinely dangerous. The entertaining entry on the list.",
            },
        ],
    },
    {
        "id": "vodka",
        "title": "Vodka: Elevating the Everyday",
        "intro": "Vodka's craft credentials. Two Dick Bradsell-era London classics and three drinks that are usually made badly and are excellent when they aren't.",
        "cocktails": [
            {
                "n": 46, "name": "Espresso Martini", "family": "Modern classic", "spirit": "Vodka",
                "ing": ["2 oz vodka", "½ oz coffee liqueur", "1 oz fresh hot espresso", "¼ oz simple syrup"],
                "method": "Shake very hard; double-strain up; three coffee beans.",
                "video": "https://www.youtube.com/watch?v=dH9DatQ_0VE", "channel": "The Educated Barfly",
                "note": "Dick Bradsell, Soho Brasserie, c. 1983, originally the Vodka Espresso. The foam only happens with genuinely fresh espresso.",
            },
            {
                "n": 47, "name": "Vesper", "family": "Martini variation", "spirit": "Vodka / Gin",
                "ing": ["3 oz gin", "1 oz vodka", "½ oz Cocchi Americano (or Lillet Blanc)"],
                "method": "Stir, despite Fleming; strain up; lemon twist.",
                "video": "https://www.youtube.com/watch?v=TzlAMAnUigE", "channel": "The Educated Barfly",
                "note": "Invented by Ian Fleming on the page in Casino Royale, 1953, and one of the few fictional cocktails that actually works.",
            },
            {
                "n": 48, "name": "Moscow Mule", "family": "Highball", "spirit": "Vodka",
                "ing": ["2 oz vodka", "½ oz fresh lime juice", "ginger beer to top"],
                "method": "Build in a copper mug over ice; lime wedge.",
                "video": "https://www.youtube.com/watch?v=oNVKUXTxqS8", "channel": "The Educated Barfly",
                "note": "The 1940s marketing scheme that built American vodka. Worth doing once with homemade ginger beer.",
            },
            {
                "n": 49, "name": "Bloody Mary", "family": "Savoury", "spirit": "Vodka",
                "ing": ["2 oz vodka", "4 oz tomato juice", "½ oz fresh lemon juice", "2 dashes Worcestershire", "2 dashes hot sauce", "pinch horseradish, salt, pepper, celery salt"],
                "method": "Roll between tins rather than shaking; highball over ice; celery and whatever else you like.",
                "video": "https://www.youtube.com/watch?v=eNXtrKFYI2Y", "channel": "The Educated Barfly",
                "note": "The great savoury cocktail and an open canvas for a house spice blend the two of you can argue about all year.",
            },
            {
                "n": 50, "name": "Cosmopolitan", "family": "Modern classic", "spirit": "Vodka",
                "ing": ["1½ oz citron vodka", "1 oz Cointreau", "½ oz fresh lime juice", "¼ oz cranberry juice"],
                "method": "Shake; strain up; flamed orange twist.",
                "video": "https://www.youtube.com/watch?v=8GuzqMeZUrM", "channel": "The Educated Barfly — 1934 variation, check before following",
                "note": "Toby Cecchini, New York, 1980s. Made with fresh lime and restrained cranberry it is dry, sharp, and nothing like its reputation.",
            },
        ],
    },
    {
        "id": "technique",
        "title": "Swizzles, Clarified & Modern Technique",
        "intro": "The capstone. Two drinks chosen for the skills they teach — swizzling and milk clarification — rather than the flavours they deliver, though both deliver.",
        "cocktails": [
            {
                "n": 30, "name": "Queen's Park Swizzle", "family": "Tiki", "spirit": "Rum",
                "ing": ["2 oz aged demerara rum", "¾ oz fresh lime juice", "½ oz demerara syrup", "8–10 mint leaves", "4+ dashes Angostura, floated"],
                "method": "Swizzle with crushed ice in a collins until frosted; mint bouquet.",
                "video": "https://www.youtube.com/watch?v=YMnUboOxII0", "channel": "The Educated Barfly",
                "note": "Trinidad's signature swizzle. The floated Angostura is both the aroma and the visual.",
            },
            {
                "n": 52, "name": "Clarified Milk Punch", "family": "Modern technique", "spirit": "Vodka / Rum / Brandy",
                "ing": ["12 oz spirit", "8 oz citrus juice", "6 oz sugar or syrup", "spices or tea to taste", "8 oz hot whole milk"],
                "method": "Stir the acidic mixture into the hot milk — never the reverse. Rest 2–24 hours refrigerated, then gravity-filter through a coffee filter until crystal clear. Serve 3–5 oz over a large cube.",
                "video": "https://www.youtube.com/watch?v=ZZ1ffluktqM", "channel": "Cocktail Chemistry",
                "note": "An eighteenth-century English technique producing a silky, shelf-stable, completely transparent punch. The showpiece to end the year on.",
            },
        ],
    },
]

# ---------------------------------------------------------------------------
# Appendix: bottles. Each row = (item, primary, alternates[], note)
# ---------------------------------------------------------------------------

APPENDIX = [
    {
        "id": "bitters-amari",
        "title": "Core bitter liqueurs & amari",
        "blurb": "The heart of the collection. Nine of the eleven groups need at least one of these.",
        "rows": [
            ("Campari", "Campari", ["Luxardo Bitter", "Contratto Bitter", "Gran Classico Bitter"],
             "Campari is proprietary. The alternates are less sweet and more herbal; Gran Classico is superb in a Boulevardier."),
            ("Aperol", "Aperol", ["Select Aperitivo", "Contratto Aperitif"],
             "Select is more bitter and rhubarb-forward — arguably a better Paper Plane."),
            ("Green Chartreuse", "Faccia Brutto Centerbe", ["Green Chartreuse", "Dolin Génépy le Chamois", "Zirbenz"],
             "Only one drink on this list needs it. The monks capped production in 2021 and moved to allocation in 2023, and nothing has changed since — so start with an alternative and treat a real bottle as a lucky find."),
            ("Yellow Chartreuse", "Strega", ["Yellow Chartreuse", "Dolin Génépy le Chamois"],
             "Also down to a single drink. Strega is sweeter and more saffron-forward: use a shade less and add lime to compensate."),
            ("Bénédictine", "D.O.M. Bénédictine", ["Drambuie (whiskey builds only)"],
             "One producer, no equivalent. Do not attempt a substitute in the Vieux Carré."),
            ("Fernet-Branca", "Fernet-Branca", ["Faccia Brutto Fernet", "Fernet Vallet"],
             "Faccia Brutto is softer and less menthol-heavy, which suits the Toronto."),
            ("Amaro Averna", "Averna", ["Amaro Meletti", "Amaro Ramazzotti"],
             "Averna's cola-and-caramel note is what makes the Black Manhattan work; Meletti is lighter and more floral."),
            ("Amaro Nonino", "Amaro Nonino Quintessentia", ["Cardamaro", "Amaro Montenegro"],
             "The grappa base is distinctive. Montenegro gives a sweeter, more floral Paper Plane."),
            ("Cynar", "Cynar", ["Cynar 70 Proof", "Bruto Americano", "Amaro CioCiaro"],
             "Cynar 70 is worth the upgrade for the Bitter Giuseppe — same profile with a spine."),
            ("Suze", "Suze", ["Salers Gentiane", "Avèze"],
             "All three make a good White Negroni. Salers is drier and more austere; Avèze rounder."),
        ],
    },
    {
        "id": "liqueurs",
        "title": "Other liqueurs",
        "blurb": "Mostly single-drink purchases, but several are irreplaceable in the drinks that need them.",
        "rows": [
            ("Maraschino liqueur", "Luxardo Maraschino", ["Maraska Maraschino"],
             "Luxardo is the reference bottle. Avoid anything labelled maraschino syrup."),
            ("Crème de violette", "Rothman &amp; Winter Crème de Violette", ["Giffard Crème de Violette", "Tempus Fugit Crème de Violette"],
             "Giffard is more floral, Tempus Fugit the most complex and the most expensive."),
            ("Triple sec / orange liqueur", "Cointreau", ["Pierre Ferrand Dry Curaçao", "Combier"],
             "Ferrand is drier and cognac-based, so better in the Crusta and Mai Tai; Cointreau better in the Cosmo and Corpse Reviver."),
            ("Orange curaçao", "Pierre Ferrand Dry Curaçao", ["Senior Curaçao of Curaçao", "Grand Marnier"],
             "The Smuggler's Cove standard for the Mai Tai."),
            ("Coffee liqueur", "Mr Black Cold Brew", ["Kahlúa", "St. George NOLA Coffee"],
             "Mr Black is far less sweet — cut or drop the added syrup in the Espresso Martini."),
            ("Velvet falernum", "John D. Taylor's Velvet Falernum", ["Latitude 29 Formula Falernum", "Homemade"],
             "Homemade — lime zest, clove, ginger, almond, rum — is a rewarding weekend project."),
            ("Allspice (pimento) dram", "St. Elizabeth Allspice Dram", ["Hamilton Pimento Liqueur", "The Bitter Truth Pimento"],
             "Hamilton is drier and more rum-forward."),
            ("Peach brandy", "Rothman &amp; Winter Orchard Peach", ["Mathilde Pêche", "Massenez Crème de Pêche"],
             "Historically this was a peach eau-de-vie; a true one is more authentic in the Fish House Punch if you can find it."),
            ("Absinthe", "St. George Absinthe Verte", ["Vieux Pontarlier", "Pernod Absinthe"],
             "You will use roughly a quarter ounce all year. One bottle is a lifetime supply."),
        ],
    },
    {
        "id": "fortified",
        "title": "Fortified & aromatized wines",
        "blurb": "All three live in the fridge and fade after six to eight weeks open. Buy 375 ml bottles wherever you can find them.",
        "rows": [
            ("Sweet vermouth", "Cocchi Vermouth di Torino", ["Carpano Antica Formula", "Punt e Mes"],
             "Cocchi is the better all-rounder and cheaper. Antica's vanilla can dominate lighter drinks; Punt e Mes is right for the Bitter Giuseppe."),
            ("Dry vermouth", "Dolin Dry", ["Noilly Prat Original Dry"],
             "Noilly is richer and more oxidative, which suits the Rosita."),
            ("Blanc aperitif", "Cocchi Americano", ["Lillet Blanc", "Kina L'Aéro d'Or"],
             "Use Cocchi for the Corpse Reviver No. 2 and the Vesper — modern Lillet lost the quinine bite those recipes were built on."),
        ],
    },
    {
        "id": "bitters",
        "title": "Bitters & aromatics",
        "blurb": "Small bottles, enormous leverage. The Trinidad Sour alone needs a full-size Angostura.",
        "rows": [
            ("Aromatic bitters", "Angostura", ["The Bitter Truth Aromatic"],
             "Nothing else has the profile at the 1½ oz the Trinidad Sour asks for."),
            ("Creole bitters", "Peychaud's", ["The Bitter Truth Creole Bitters"],
             "Non-negotiable for the Vieux Carré and À La Louisiane."),
            ("Orange bitters", "Regans' Orange No. 6", ["Angostura Orange", "Fee Brothers West Indian Orange"],
             "Many bartenders run a 50/50 blend of Regans' and Fee's."),
            ("Mole / chocolate bitters", "Bittermens Xocolatl Mole", ["Fee Brothers Aztec Chocolate"],
             "Optional, but it transforms the Oaxaca Old Fashioned."),
            ("Orange flower water", "Nielsen-Massey Orange Blossom Water", ["A. Monteux", "Cortas"],
             "Ramos only. Dashes, not splashes — it goes soapy immediately."),
        ],
    },
    {
        "id": "syrups",
        "title": "Tiki components & syrups",
        "blurb": "The homemade items here move the needle more than any bottle upgrade on the page.",
        "rows": [
            ("Orgeat", "Small Hand Foods Orgeat", ["Liber &amp; Co. Orgeat", "Latitude 29 Formula Orgeat", "Homemade"],
             "The single biggest upgrade available. It matters most in the Japanese Cocktail and Trinidad Sour, where orgeat is a lead flavour."),
            ("Cream of coconut", "Coco López", ["Coco Reàl", "Real Cream of Coconut"],
             "Stir the can thoroughly before measuring; it separates hard."),
            ("Raspberry syrup", "Small Hand Foods Raspberry Gum", ["Liber &amp; Co. Raspberry Gum", "Homemade"],
             "Equal parts fresh raspberries, sugar and water is easy and better than anything bottled."),
            ("Demerara / rich syrup", "Homemade 2:1", ["Liber &amp; Co. Demerara Gum"],
             "Use Billington's or Florida Crystals demerara sugar."),
            ("Honey syrup", "Homemade 3:1", [],
             "Local wildflower or orange blossom honey. Clover honey tastes flat in the Gold Rush and Bee's Knees."),
            ("Ginger beer", "Fever-Tree Ginger Beer", ["Q Ginger Beer", "Bundaberg"],
             "For the Penicillin use fresh juiced ginger in the syrup rather than any bottled shortcut."),
            ("Grapefruit soda", "Jarritos Toronja", ["Squirt", "Fever-Tree Sparkling Grapefruit"],
             "Squirt is the traditional Mexican choice; Fever-Tree is drier and more adult."),
            ("Tomato juice", "Sacramento Tomato Juice", ["Clamato", "RW Knudsen"],
             "Sacramento is the bartender default because of its body."),
            ("Cocktail cherries", "Luxardo Maraschino Cherries", ["Fabbri Amarena", "Jack Rudy Bourbon Cherries"],
             "Never the neon ones."),
        ],
    },
    {
        "id": "rum",
        "title": "Rum",
        "blurb": "Seven styles, and the tiki group genuinely needs the distinctions between them.",
        "rows": [
            ("Overproof Jamaican", "Smith &amp; Cross", ["Rum Fire", "Worthy Park 109"], "Kingston Negroni."),
            ("Aged Jamaican", "Appleton Estate 12 Year", ["Hamilton Jamaican Pot Still Gold", "Doctor Bird"], "Mai Tai, Fish House Punch."),
            ("Demerara", "Hamilton 86 Demerara", ["El Dorado 12", "Lemon Hart Original 1804"], "Queen's Park Swizzle."),
            ("Blackstrap", "Cruzan Black Strap", ["Gosling's Black Seal", "Plantation O.F.T.D."], "Jungle Bird, Corn 'n' Oil."),
            ("Rhum agricole vieux", "Rhum J.M VSOP", ["Clément VSOP", "La Favorite Cœur de Canne"], "Three Dots and a Dash."),
            ("Navy rum", "Pusser's Gunpowder Proof", ["Smith &amp; Cross"], "Painkiller."),
            ("White / light rum", "Probitas (Veritas)", ["Havana Club 3", "Plantation 3 Stars", "Flor de Caña 4"], "Hemingway Daiquiri."),
        ],
    },
    {
        "id": "whiskey",
        "title": "Whiskey",
        "blurb": "Bonded rye does most of the work here. Buy the 100-proof bottles — the drinks are built for them.",
        "rows": [
            ("Rye, 100 proof", "Rittenhouse Rye Bottled-in-Bond", ["Wild Turkey 101 Rye", "Old Forester Rye"], "Final Ward, Black Manhattan, Toronto, Old Pal, À La Louisiane."),
            ("Bourbon", "Old Forester 100 Proof", ["Wild Turkey 101", "Elijah Craig Small Batch"], "Paper Plane, Gold Rush, Benton's, Boulevardier."),
            ("Blended Scotch", "Monkey Shoulder", ["Compass Box Great King Street", "The Famous Grouse"], "Penicillin base."),
            ("Islay single malt", "Laphroaig 10", ["Ardbeg 10", "Lagavulin 16"], "Penicillin float. Lagavulin is the original spec but expensive to pour a quarter ounce of."),
        ],
    },
    {
        "id": "brandy-bottles",
        "title": "Brandy",
        "blurb": "One good cognac covers five drinks. The bonded apple brandy covers two more.",
        "rows": [
            ("Cognac", "Pierre Ferrand 1840 Original Formula", ["Hine H by Hine", "Rémy Martin VSOP", "Camus VSOP"], "Built specifically for cocktails — Ferrand 1840 is the bartender's default."),
            ("Apple brandy / Calvados", "Laird's Straight Apple Brandy Bottled-in-Bond", ["Christian Drouin Sélection", "Busnel VSOP"], "Widow's Kiss, Corpse Reviver No. 1. Note that Laird's Applejack is a different, blended product."),
            ("Pisco", "Campo de Encanto", ["Macchu Pisco", "BarSol", "Caravedo"], "Pisco Sour."),
        ],
    },
    {
        "id": "agave-bottles",
        "title": "Agave",
        "blurb": "All should be 100% agave and additive-free. Skip the celebrity bottles entirely.",
        "rows": [
            ("Blanco tequila", "Cimarrón Blanco", ["Espolòn Blanco", "Arette Blanco", "Tapatío 110"], "Siesta, Paloma, Tommy's Margarita."),
            ("Reposado tequila", "Siete Leguas Reposado", ["Cimarrón Reposado", "El Tesoro Reposado", "Espolòn Reposado"], "Oaxaca Old Fashioned, Rosita."),
            ("Mezcal", "Del Maguey Vida", ["Banhez Ensamble", "Xicaru Silver", "Bozal Ensamble"], "Naked &amp; Famous, Division Bell, Oaxaca Old Fashioned."),
        ],
    },
    {
        "id": "gin-vodka",
        "title": "Gin & vodka",
        "blurb": "Beefeater does everything the gin drinks need. Spend the difference on Chartreuse.",
        "rows": [
            ("London dry gin", "Beefeater London Dry", ["Fords Gin", "Tanqueray", "Sipsmith"], "Last Word, Corpse Reviver No. 2, Hanky Panky, White Negroni."),
            ("Gin for floral & herbal builds", "Fords Gin", ["Plymouth Gin", "Hayman's London Dry"], "Aviation, Gin Basil Smash, Clover Club."),
            ("Vodka", "Ketel One", ["Wheatley Vodka", "Absolut Elyx", "Tito's"], "Espresso Martini, Vesper, Mule, Bloody Mary."),
            ("Citrus vodka", "Absolut Citron", ["Ketel One Citroen"], "Cosmopolitan."),
        ],
    },
]

WAVES = [
    ("Wave one", "Buy first — these unlock the most drinks per dollar.",
     ["Campari", "Luxardo Maraschino", "Cocchi Vermouth di Torino", "Dolin Dry Vermouth", "Cocchi Americano",
      "Angostura Bitters", "Peychaud's Bitters", "Regans' Orange Bitters No. 6", "Beefeater Gin",
      "Rittenhouse Rye", "Old Forester 100 Proof", "Cointreau"]),
    ("Wave two", "The backbone of the middle of the year.",
     ["Aperol", "Bénédictine", "Punt e Mes", "Pierre Ferrand 1840 Cognac",
      "Cimarrón Blanco Tequila", "Del Maguey Vida Mezcal", "Appleton Estate 12", "Smith &amp; Cross Rum"]),
    ("Wave three", "Specialty and drink-specific. Buy as the calendar reaches them.",
     ["Suze", "Cynar", "Fernet-Branca", "Amaro Averna", "Amaro Nonino", "Rothman &amp; Winter Crème de Violette",
      "Velvet Falernum", "St. Elizabeth Allspice Dram", "Hamilton 86 Demerara", "Rhum J.M VSOP",
      "Pusser's Rum", "Laird's Bottled-in-Bond Apple Brandy", "Campo de Encanto Pisco",
      "Rothman &amp; Winter Orchard Peach", "Laphroaig 10", "Mr Black Coffee Liqueur",
      "Faccia Brutto Centerbe", "Strega", "Small Hand Foods Grenadine"]),
]
